### ISSUE TITLE
Keine Felder für die Google-Schlüssel (Contao 4.7.1)

### ISSUE THREAD

**Issue by lucasdidthis** [wschern/rsm-googlerecaptcha-modul#1]
Hej!

Ersteinmal vielen Dank für das Plugin. Leider habe ich ein Problem:

Ich habe das Plugin installiert und das entsprechende Feld ist anschließend auch im Formulargenerator verfügbar. Leider tauchen in den Einstellungen des Startpunkt der Website keine Felder auf, um die Captcha-Keys von Google einzutragen. Ich bekomme aber auch keinerlei Fehlermeldung - abgesehen von der Meldung im Formular im Frontend, dass ich die Schlüssel eintragen soll.

Version-Infos:
das Contao ist Version 4.7.1
der Contao Manager ist Version 1.1.4
das rsm-googlerecaptcha-modul wurde über den Manager installiert und ist Version 1.0.0

Bei alten Contaos hatte ich das Problem nicht. :-/
Ich wäre sehr über Hilfe dankbar!

Liebe Grüße
Lucas

**Comment by Paddy0174** [comment]
Habe gerade einen PR ( #2 ) dazu gemacht. Sollte also bald erledigt sein. :)

**Comment by wschern** [comment]
Hallo @lucasdidthis,

und danke für das positive Feedback. Die Struktur von Paletten hat sich seit Contao 4.4 leicht verändert und mein Code war in dieser Hinsicht leider nicht flexibel genug. Vielen Dank an  @Paddy0174 für den PR.
