### ISSUE TITLE
[1.0.3] Fehler in Contao 4.8

### ISSUE THREAD

**Issue by mj1985** [wschern/rsm-googlerecaptcha-modul#4]
Moin,
unter Contao 4.8 tritt leider folgender Fehler auf:
![image](https://user-images.githubusercontent.com/5830093/76307468-2bbd5b80-62c9-11ea-9f3a-cfe5de865add.png)

Ein Downgrade auf die Version 1.0.2 löst das Problem. Leider ist bei dieser Kundeninstallation aufgrund von PHP 7.1 kein Update auf Contao 4.9 möglich, was das Problem natürlich auch löst.

**Comment by dhaeb** [comment]
Hey,
hatte eine ähnlichen Fehler mit Contao 4.4.47... ich probiere jetzt das Downgrade auf 1.0.2 - danke für das Issue & das tolle Plugin-

Beste Grüße

**Comment by mj1985** [comment]
@dhaeb Downgrade funktioniert. Als Workaround in der composer.json folgendes eintragen:

```
    "conflict": {
        "rsm/rsm-googlerecaptcha-modul": "1.0.3"
    },
```

**Comment by dhaeb** [comment]
@mj1985 danke für den Hinweis, die folgende Konfiguration hat aber auch gereicht:
```
   "require": {
....
       	"rsm/rsm-googlerecaptcha-modul" : "1.0.2"
}
```

**Comment by Sarahsolus** [comment]
Kann ich bestätigen. Mein Contao 4.4.47 wirft auch den rootfallback-Fehler, wenn ich die Erweiterung installieren will.

**Comment by wschern** [comment]
Gefixt in 1.0.4
